### ISSUE TITLE
[Research Jenkins] Set up Jenkins to SSH into the server

### ISSUE THREAD

**Issue by tuanhcmute** [tuanhcmute/topic-registration-service#6]
[Research Jenkins] Set up Jenkins to SSH into the server

**Comment by tuanhcmute** [comment]
[Config  SSH from Jenkins to EC2 Instance.docx](https://github.com/tuanhcmute/topic-registration-service/files/12561176/Config.SSH.from.Jenkins.to.EC2.Instance.docx)

**Comment by tuanhcmute** [comment]
Hi @PhamNguyenNhutTruong, Could you please show me how to run multiple commands on Ubuntu ?

**Comment by PhamNguyenNhutTruong** [comment]
Hello @tuanhcmute 
Of course you can run multiple commands in a path script from Jenkins to SSH to Ubuntu server ( EC2 Instance). Follow below step to solve your problem:
**Image:**
![image](https://github.com/tuanhcmute/topic-registration-service/assets/89334096/002ebcf6-382d-486f-8ebf-5dee27280a25)
**Pipeline Script**
```
pipeline {
    agent any
    environment {
        MY_SSH_KEY = credentials('ssh-agent')
    }
    stages {
        stage('SSH to EC2') {
            steps {
                withCredentials([sshUserPrivateKey(credentialsId: 'ssh-agent', keyFileVariable: 'MY_SSH_KEY')]) {
                    sh '''
                        ssh-keyscan -H 54.172.193.47 >> ~/.ssh/known_hosts
                        ssh -i ${MY_SSH_KEY} ubuntu@54.172.193.47 "mkdir NewFolder, mkdir NewFolder2"
                    '''
                }
            }
        }
    }
}
```

**Comment by tuanhcmute** [comment]
Thanks @PhamNguyenNhutTruong, your information is very helpful
