### ISSUE TITLE
Survey similar Websites

### ISSUE THREAD

**Issue by tuanhcmute** [tuanhcmute/topic-registration-service#9]
Survey similar Websites:
- Survey at least 80% of websites with similar functions (https://pgm.hcmute.edu.vn), (https://www.youtube.com/watch?v=zPbda1eiPew&list=PLibFbayumkJ43t6iQFZxsXRhWl6cdh38c)

**Comment by tuanhcmute** [comment]
[HDSD_SauDaiHoc_HocVien.pdf](https://github.com/tuanhcmute/topic-registration-service/files/12562041/HDSD_SauDaiHoc_HocVien.pdf)
- Hi @PhamNguyenNhutTruong, Could you please take some notes on **Student features** of the [PGM website](https://pgm.hcmute.edu.vn/)?

**Comment by PhamNguyenNhutTruong** [comment]
ok @tuanhcmute I will make it.

**Comment by tuanhcmute** [comment]
> ok @tuanhcmute I will make it.

 - Hi @PhamNguyenNhutTruong, Could you please complete this task as soon as possible? 
- For me, I will try to update my status soon.

**Comment by PhamNguyenNhutTruong** [comment]
Hello @tuanhcmute
I apologize for this delay.
Below is a summary of the student functions that I surveyed on the YouTube channel [Trung tâm Công nghệ Phần mềm STC HCMUTE](https://www.youtube.com/@trungtamcongnghephanmemstc3222/playlists) in the section [SDH-Học viên](https://youtube.com/playlist?list=PLibFbayumkJ6FfMUbuYpIOHd1pdgI3F1x&si=1BpjEFCD4IYeuYUD)
You can view the report [here](https://docs.google.com/document/d/13Wh5XGqAwd_4hkACAU6OlbL-lHIk0A0kr6cMyCGmcrY/edit?usp=sharing)

**Comment by tuanhcmute** [comment]
[Khảo sát Website quản lý đề tài sau đại học.docx](https://github.com/tuanhcmute/topic-registration-service/files/12641952/Kh.o.sat.Website.qu.n.ly.d.tai.sau.d.i.h.c.docx)
Done
